### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ezeekieel** [M4ND33P-M4L4K4R143/Termux-Login#5]
Hello, I recently installed "Termux-Login" which works very well, but I'd like to know how to uninstall it? Ps:I have not forgotten my password for the script.

 
Thanks for reading 
Sincerely, SilentUnknow

**Comment by tagda-coder** [comment]
Just open Termux and Type, 
cd $HOME
rm -rf Termux-Login

And restart your termux...
